version: "2"

services:
  node:
    image: "node:14-alpine"
    user: "node"
    working_dir: "/home/node/app"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    expose:
      - "8081"
    command: "npm start"
  
